### ISSUE TITLE
为什么文章和源码都难以找到?

### ISSUE THREAD

**Issue by 79zzz** [LlistenL/MLPMatch#1]

**Comment by LlistenL** [comment]
你好，或许你可以先从以下链接获取该paper：https://link.springer.com/chapter/10.1007/978-981-97-8858-3_11，代码检查无误后便会开源。

**Comment by 79zzz** [comment]
页面显示未找到

**Comment by LlistenL** [comment]
https://link.springer.com/chapter/10.1007/978-981-97-8858-3_11
